# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 32cf92edd305d96b8b35176461da9b92b740a8101a1df4a25b49f75ef257d2263261e47c8f460a7b8f7591f2da8615b51e00bf6151ac8ee3c1fc77c03c46319d

test:
  secret_key_base: 3caf8d061dac992e026f614170e82fefded61fe94c643b28da4df6c75c0da3cc70a0064bf3738d495bd4d3e049ccbd4f78d21dfef4ca3408810604ad952b1550

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
